# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_favorites_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='author',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='content',
        ),
        migrations.AddField(
            model_name='favorites',
            name='quote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='quotes.Quotes'),
            preserve_default=False,
        ),
    ]
